### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: 1.1.0 Release

# What does this Pull Request do?

Fixes Travis.

# What's new?

A `chmod` to get past Drupal's permissions hardening on installation.

# How should this be tested?

Travis should be green.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by whikloj** [comment]
Well that cleared up the deprecations but we do have some actual issues around injecting the entity_type.manager service. Is this a Drupal version thing maybe?

https://travis-ci.com/github/Islandora/jsonld/jobs/301293663#L2695-L2696

**Comment by dannylamb** [comment]
I'm uncovering all kinds of goodies...  I'll see what's up.

**Comment by whikloj** [comment]
Oh actually its a typo I think `entity_type.manager.manager`

**Comment by whikloj** [comment]
Not sure from where, maybe this call?
https://github.com/Islandora/jsonld/blob/8.x-1.x/tests/src/Kernel/JsonldKernelTestBase.php#L180

**Comment by whikloj** [comment]
Almost there, just some unused imports.

**Comment by dannylamb** [comment]
:relieved:

**Pull request merged**
